import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f5f6f7",
        "outline-variant": "#abadae",
        "on-primary-fixed-variant": "#002a61",
        "on-surface-variant": "#595c5d",
        "secondary": "#755700",
        "primary": "#0058bb",
        "on-background": "#2c2f30",
        "surface-container-low": "#eff1f2",
        "on-error": "#ffefee",
        "tertiary-dim": "#962700",
        "on-tertiary-fixed-variant": "#6f1a00",
        "on-tertiary-container": "#601500",
        "on-error-container": "#570008",
        "on-tertiary": "#ffefeb",
        "outline": "#757778",
        "on-primary-fixed": "#000000",
        "surface-container-high": "#e0e3e4",
        "tertiary-container": "#ff9475",
        "error": "#b31b25",
        "background": "#f5f6f7",
        "inverse-primary": "#4b8eff",
        "error-dim": "#9f0519",
        "on-surface": "#2c2f30",
        "on-secondary": "#fff1db",
        "error-container": "#fb5151",
        "surface-bright": "#f5f6f7",
        "on-primary": "#f0f2ff",
        "secondary-dim": "#664b00",
        "tertiary-fixed-dim": "#ff7d57",
        "on-primary-container": "#00214f",
        "surface-variant": "#dadddf",
        "primary-fixed-dim": "#5191ff",
        "on-secondary-fixed": "#443100",
        "secondary-container": "#ffca4d",
        "surface-tint": "#0058bb",
        "secondary-fixed": "#ffca4d",
        "tertiary": "#ab2d00",
        "on-tertiary-fixed": "#340800",
        "primary-dim": "#004ca4",
        "surface-dim": "#d1d5d7",
        "inverse-on-surface": "#9b9d9e",
        "secondary-fixed-dim": "#f7ba00",
        "tertiary-fixed": "#ff9475",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#0c0f10",
        "surface-container-highest": "#dadddf",
        "primary-container": "#6c9fff",
        "surface-container": "#e6e8ea",
        "on-secondary-fixed-variant": "#674c00",
        "primary-fixed": "#6c9fff",
        "on-secondary-container": "#5c4400",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Be Vietnam Pro", "sans-serif"],
        label: ["Be Vietnam Pro", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
